server:
  # 端口
  port: 8080
  servlet:
    # 首页路径
    context-path: /


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: aiNI@13141
    driver-class-name: com.mysql.cj.jdbc.Driver
